# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import example_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('featured', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('length', models.CharField(blank=True, max_length=24, null=True)),
                ('feature_image', models.FileField(upload_to=example_app.models.image_upload_to)),
                ('cover_image', models.FileField(upload_to=example_app.models.image_upload_to)),
                ('video', models.URLField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_set', to='example_app.Category')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='videos',
            field=models.ManyToManyField(related_name='collections', to='example_app.Video'),
        ),
    ]
